#!/usr/bin/env bash
if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ]; then
    exec gosu $WWWUSER "$@"
else
    /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf


echo "🚀 Dump Autoloader"
composer dumpautoload


echo "🚀 Clearing Cache/Views/Configs"
php artisan view:clear
php artisan config:clear
php artisan cache:clear
php artisan migrate
php artisan db:seed --class=DatabaseSeeder

if [ -n "$RUNNING_IN_VOYAGE" ] || [ -n "$CIRCLECI" ] || [ "$APP_ENV" = "local" ]; then
echo "🚀 Running migrations & Seeder"
  php artisan migrate --force
  php artisan db:seed --class=DatabaseSeeder
fi