apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-cluster-secrets-store
spec:
  provider:
    gcpsm:
      projectID: sparkbooks-app
      auth:
        workloadIdentity:
          clusterLocation: us-south1-a
          clusterName: sparkbooks-cluster
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
