apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghcr-pull-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-cluster-secrets-store
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: "{{`{{ .secret | toString }}`}}"
    name: ghcr-pull-secret
    creationPolicy: Owner
  data:
    - secretKey: secret
      remoteRef:
        key: ghcr_token