apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sparkbooks.serviceAccountName" . }}
  labels:
    {{- include "sparkbooks.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}