apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparksbooks-server
  namespace: web
spec:
  selector:
    matchLabels:
      run: sparksbooks-server
  template:
    metadata:
      labels:
        run: sparksbooks-server
    spec:
      serviceAccountName: sparksbook-backend
      volumes:
        - name: secrets
          emptyDir: { }
      initContainers:
        - name: secrets-init
          image: google/cloud-sdk:slim
          command:
            - sh
          args:
            - -c
            - "gcloud secrets versions access 1 --secret=test-cluster-db-secrets > /secrets/env"
          volumeMounts:
            - mountPath: /secrets/
              name: secrets
      containers:
      - image: gcr.io/pdf-scanner-346920/sparksbook-app/sparksbooks-server:a5457aec22e928a2d8fc7b35c6484be9e0e12e64
        imagePullPolicy: IfNotPresent
        name: sparksbooks-server
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
        env:
        - name: "APP_PORT"
          value: "8080"
        - name: KEY1
          valueFrom:
            configMapKeyRef:
              name: sparksbook-backend-config
              key: key1
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: APP_NAME
              key: APP_NAME
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: APP_ENV
              key: APP_ENV
        - name: APP_KEY
          valueFrom:
            configMapKeyRef:
              name: APP_KEY
              key: APP_KEY
        - name: APP_DEBUG
          valueFrom:
            configMapKeyRef:
              name: APP_DEBUG
              key: APP_DEBUG
        - name: APP_URL
          valueFrom:
            configMapKeyRef:
              name: APP_URL
              key: APP_URL
        - name: FRONTEND_URL
          valueFrom:
            configMapKeyRef:
              name: FRONTEND_URL
              key: FRONTEND_URL
        - name: LOG_CHANNEL
          valueFrom:
            configMapKeyRef:
              name: LOG_CHANNEL
              key: LOG_CHANNEL
        - name: LOG_DEPRECATIONS_CHANNEL
          valueFrom:
            configMapKeyRef:
              name: LOG_DEPRECATIONS_CHANNEL
              key: LOG_DEPRECATIONS_CHANNEL
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: LOG_LEVEL
              key: LOG_LEVEL
        - name: DB_CONNECTION
          valueFrom:
            configMapKeyRef:
              name: DB_CONNECTION
              key: DB_CONNECTION
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: DB_HOST
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: DB_PORT
              key: DB_PORT
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: DB_DATABASE
              key: DB_DATABASE
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: DB_USERNAME
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: DB_PASSWORD
              key: DB_PASSWORD
        - name: BROADCAST_DRIVER
          valueFrom:
            configMapKeyRef:
              name: BROADCAST_DRIVER
              key: BROADCAST_DRIVER
        - name: CACHE_DRIVER
          valueFrom:
            configMapKeyRef:
              name: CACHE_DRIVER
              key: CACHE_DRIVER
        - name: FILESYSTEM_DISK
          valueFrom:
            configMapKeyRef:
              name: FILESYSTEM_DISK
              key: FILESYSTEM_DISK
        - name: QUEUE_CONNECTION
          valueFrom:
            configMapKeyRef:
              name: QUEUE_CONNECTION
              key: QUEUE_CONNECTION
        - name: SESSION_DRIVER
          valueFrom:
            configMapKeyRef:
              name: SESSION_DRIVER
              key: SESSION_DRIVER
        - name: SESSION_LIFETIME
          valueFrom:
            configMapKeyRef:
              name: SESSION_LIFETIME
              key: SESSION_LIFETIME
        - name: SESSION_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: SESSION_DOMAIN
              key: SESSION_DOMAIN
        - name: MEMCACHED_HOST
          valueFrom:
            configMapKeyRef:
              name: MEMCACHED_HOST
              key: MEMCACHED_HOST
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: REDIS_HOST
              key: REDIS_HOST
        - name: REDIS_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: REDIS_PASSWORD
              key: REDIS_PASSWORD
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: REDIS_PORT
              key: REDIS_PORT
        - name: MAIL_MAILER
          valueFrom:
            configMapKeyRef:
              name: MAIL_MAILER
              key: MAIL_MAILER
        - name: MAIL_HOST
          valueFrom:
            configMapKeyRef:
              name: MAIL_HOST
              key: MAIL_HOST
        - name: MAIL_PORT
          valueFrom:
            configMapKeyRef:
              name: MAIL_PORT
              key: MAIL_PORT
        - name: MAIL_USERNAME
          valueFrom:
            configMapKeyRef:
              name: MAIL_USERNAME
              key: MAIL_USERNAME
        - name: MAIL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: MAIL_PASSWORD
              key: MAIL_PASSWORD
        - name: MAIL_ENCRYPTION
          valueFrom:
            configMapKeyRef:
              name: MAIL_ENCRYPTION
              key: MAIL_ENCRYPTION
        - name: MAIL_FROM_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: MAIL_FROM_ADDRESS
              key: MAIL_FROM_ADDRESS
        - name: MAIL_FROM_NAME
          valueFrom:
            configMapKeyRef:
              name: MAIL_FROM_NAME
              key: MAIL_FROM_NAME
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            configMapKeyRef:
              name: AWS_ACCESS_KEY_ID
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            configMapKeyRef:
              name: AWS_SECRET_ACCESS_KEY
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_DEFAULT_REGION
          valueFrom:
            configMapKeyRef:
              name: AWS_DEFAULT_REGION
              key: AWS_DEFAULT_REGION
        - name: AWS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: AWS_BUCKET
              key: AWS_BUCKET
        - name: AWS_USE_PATH_STYLE_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: AWS_USE_PATH_STYLE_ENDPOINT
              key: AWS_USE_PATH_STYLE_ENDPOINT
        - name: PUSHER_APP_ID
          valueFrom:
            configMapKeyRef:
              name: PUSHER_APP_ID
              key: PUSHER_APP_ID
        - name: PUSHER_APP_KEY
          valueFrom:
            configMapKeyRef:
              name: PUSHER_APP_KEY
              key: PUSHER_APP_KEY
        - name: PUSHER_APP_SECRET
          valueFrom:
            configMapKeyRef:
              name: PUSHER_APP_SECRET
              key: PUSHER_APP_SECRET
        - name: PUSHER_APP_CLUSTER
          valueFrom:
            configMapKeyRef:
              name: PUSHER_APP_CLUSTER
              key: PUSHER_APP_CLUSTER
        - name: MIX_PUSHER_APP_KEY
          valueFrom:
            configMapKeyRef:
              name: MIX_PUSHER_APP_KEY
              key: MIX_PUSHER_APP_KEY
        - name: MIX_PUSHER_APP_CLUSTER
          valueFrom:
            configMapKeyRef:
              name: MIX_PUSHER_APP_CLUSTER
              key: MIX_PUSHER_APP_CLUSTER
        - name: GOOGLE_CLOUD_PROJECT_ID
          valueFrom:
            configMapKeyRef:
              name: GOOGLE_CLOUD_PROJECT_ID
              key: GOOGLE_CLOUD_PROJECT_ID
        - name: GOOGLE_CLOUD_STORAGE_BUCKET
          valueFrom:
            configMapKeyRef:
              name: GOOGLE_CLOUD_STORAGE_BUCKET
              key: GOOGLE_CLOUD_STORAGE_BUCKET
        - name: GCP_AI_PROCESSOR
          valueFrom:
            configMapKeyRef:
              name: GCP_AI_PROCESSOR
              key: GCP_AI_PROCESSOR
        - name: # OAuth C
          valueFrom:
            configMapKeyRef:
              name: # OAuth C
              key: # OAuth C
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: GOOGLE_CLIENT_ID
              key: GOOGLE_CLIENT_ID
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            configMapKeyRef:
              name: GOOGLE_CLIENT_SECRET
              key: GOOGLE_CLIENT_SECRET
        - name: GOOGLE_REDIRECT_URI
          valueFrom:
            configMapKeyRef:
              name: GOOGLE_REDIRECT_URI
              key: GOOGLE_REDIRECT_URI
        - name: GCP_BUCKET_DIRECTORY
          valueFrom:
            configMapKeyRef:
              name: GCP_BUCKET_DIRECTORY
              key: GCP_BUCKET_DIRECTORY
        - name: GITHUB_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: GITHUB_CLIENT_ID
              key: GITHUB_CLIENT_ID
        - name: GITHUB_CLIENT_SECRET
          valueFrom:
            configMapKeyRef:
              name: GITHUB_CLIENT_SECRET
              key: GITHUB_CLIENT_SECRET
        - name: GITHUB_REDIRECT_URI
          valueFrom:
            configMapKeyRef:
              name: GITHUB_REDIRECT_URI
              key: GITHUB_REDIRECT_URI
        - name: BASE_PW
          valueFrom:
            configMapKeyRef:
              name: BASE_PW
              key: BASE_PW
        - name: STRIPE_KEY
          valueFrom:
            configMapKeyRef:
              name: STRIPE_KEY
              key: STRIPE_KEY
        - name: STRIPE_SECRET
          valueFrom:
            configMapKeyRef:
              name: STRIPE_SECRET
              key: STRIPE_SECRET
        - name: STRIPE_WEBHOOK_SECRET
          valueFrom:
            configMapKeyRef:
              name: STRIPE_WEBHOOK_SECRET
              key: STRIPE_WEBHOOK_SECRET
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
          - mountPath: /secrets/
            name: secrets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparksbooks-frontend
  namespace: web
spec:
  selector:
    matchLabels:
      run: sparksbooks-frontend
  template:
    metadata:
      labels:
        run: sparksbooks-frontend
    spec:
      containers:
      - image: gcr.io/pdf-scanner-346920/sparksbook-app/sparksbooks-frontend:a5457aec22e928a2d8fc7b35c6484be9e0e12e64
        imagePullPolicy: IfNotPresent
        name: sparksbooks-frontend
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
        env:
        - name: "APP_PORT"
          value: "8081"
        - name: "PORT"
          value: "8081"
        - name: KEY1
          valueFrom:
            configMapKeyRef:
              name: sparksbook-frontend-config
              key: key1
        - name: KEY2
          valueFrom:
            configMapKeyRef:
              name: sparksbook-frontend-config
              key: key2
        ports:
        - containerPort: 8081
          protocol: TCP
