apiVersion: v1
kind: Service
metadata:
  name: sparksbooks-server
  namespace: web
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    run: sparksbooks-server
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sparksbooks-frontend
  namespace: web
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    run: sparksbooks-frontend
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081