apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sparkbooks.fullname" . }}-frontend
  labels:
    {{- include "sparkbooks.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      serviceAccountName: {{ include "sparkbooks.serviceAccountName" . }}
      containers:
        - name: sparkbooks-frontend
          image: "{{ .Values.frontend.image }}"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
