apiVersion: v1
kind: Service
metadata:
  name: {{ include "sparkbooks.fullname" . }}-frontend
  labels:
    {{- include "sparkbooks.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: frontend
