name: Build & Publish Front-End Docker Image

on:
  push:
    paths:
      - ".github/workflows/build-push-frontend.yaml"
      - "frontend/**"
    branches:
      # @TODO update branch
      - jaden
jobs:
  push_to_registry:
    name: Push Docker image to GHCR
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          tags: |
            type=raw,value=latest
            type=sha
            type=ref,event=branch
          images: |
            ghcr.io/danielfrance/sparkbooks-ui

      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          context: frontend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
